- name: Debug and Deploy
        run: |
          npx wrangler whoami
          npx wrangler pages deploy . --project-name=trevainnovate --branch=main --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          # POR FAVOR: DESCOMENTA LA LINEA DE ABAJO SI LA TENIAS, 
          # PERO SI SIGUE FALLANDO, BORRA EL ACCOUNT_ID DE TUS SECRETS Y NO LO PASES
          # CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
